events {
    # Nginx necesita este bloque aunque esté vacío. Define cómo maneja las conexiones simultáneas.
    worker_connections 1024;
}

http {
    # Incluimos los tipos de archivo estándar (para que entienda qué es un .html o un .css)
    include /etc/nginx/mime.types;

    server {
        # Escuchamos en el puerto estándar de internet
        listen 80;

        # ----------------------------------------------------
        # ROL 1: SERVIDOR WEB (Frontend)
        # ----------------------------------------------------
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # ----------------------------------------------------
        # ROL 2: PROXY INVERSO (Backend / API)
        # ----------------------------------------------------
        location /agregar {
            proxy_pass http://flask-app:8000;
        }

        location /mascotas {
            proxy_pass http://flask-app:8000;
        }

        location /solicitudes {
            proxy_pass http://flask-app:8000;
        }

        location /login {
            proxy_pass http://flask-app:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    
        location /usuarios {
            proxy_pass http://flask-app:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /uploads/ {
            alias /usr/share/nginx/uploads/;
        }
        
        location /admin {
            proxy_pass http://flask-app:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}