events {
    # Nginx necesita este bloque aunque esté vacío. Define cómo maneja las conexiones simultáneas.
    worker_connections 1024;
}

http {
    # Incluimos los tipos de archivo estándar (para que entienda qué es un .html o un .css)
    include /etc/nginx/mime.types;

    server {
        # Escuchamos en el puerto estándar de internet
        listen 80;

        # ----------------------------------------------------
        # ROL 1: SERVIDOR WEB (Frontend)
        # ----------------------------------------------------
        # Cuando alguien entre a "localhost/" (la raíz), Nginx buscará los archivos aquí
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # ----------------------------------------------------
        # ROL 2: PROXY INVERSO (Backend / API)
        # ----------------------------------------------------
        # Si la petición incluye estas rutas, Nginx NO busca archivos. 
        # En su lugar, actúa como cartero y reenvía el paquete al contenedor de Flask.
        
        location /agregar {
            proxy_pass http://flask-app:8000;
        }

        location /mascotas {
            proxy_pass http://flask-app:8000;
        }

        # Dejamos preparadas las rutas de los otros módulos que programaste en app.py
        location /usuarios {
            proxy_pass http://flask-app:8000;
        }

        location /solicitudes {
            proxy_pass http://flask-app:8000;
        }
    }
}
